// Sofdec runtime translation-unit assembly grouped by subsystem ownership.
#include "cri/sofdec/SofdecFoundationRuntime.cpp"
#include "cri/sofdec/SofdecAdxRuntime.cpp"
#include "cri/sofdec/SofdecSvmTransferRuntime.cpp"
#include "cri/sofdec/SofdecSfdRuntime.cpp"
#include "cri/sofdec/SofdecMwPlaybackRuntime.cpp"
#include "cri/sofdec/SofdecVirtualDispatchRuntime.cpp"
#include "cri/sofdec/SofdecAdxbBootstrapRuntime.cpp"
#include "cri/sofdec/SofdecAdxCodecRuntime.cpp"
#include "cri/sofdec/SofdecMpaRuntime.cpp"
#include "cri/sofdec/SofdecM2aDecoderRuntime.cpp"
#include "cri/sofdec/SofdecVirtualDispatchTableRuntime.cpp"
