#pragma once

#include <typeinfo>

namespace moho
{
  /**
   * Runtime RTTI descriptor owned by the MSVC CRT (`.?AVtype_info@@`),
   * not a Moho-specific class.
   *
   * Address: 0x00A8244A (`??_Etype_info@@UAEPAXI@Z`, vector deleting dtor)
   */
  using RuntimeTypeInfo = std::type_info;

  /**
   * Address: 0x00A8247D (`??8type_info@@QBE_NABV0@@Z`, `type_info::operator==`)
   *
   * Compares canonical runtime type descriptors for equality.
   */
  [[nodiscard]] bool RuntimeTypeEquals(const RuntimeTypeInfo& lhs, const RuntimeTypeInfo& rhs) noexcept;

  /**
   * Address: 0x00A8242D (`?name@type_info@@QBEPBDPAU__type_info_node@@@Z`, `type_info::name`)
   *
   * Returns canonical runtime type name.
   */
  [[nodiscard]] const char* RuntimeTypeName(const RuntimeTypeInfo& typeInfo) noexcept;

  /**
   * Address: 0x00A824B4 (`?before@type_info@@QBEHABV1@@Z`, `type_info::before`)
   *
   * Strict weak ordering used by RTTI maps.
   */
  [[nodiscard]] bool RuntimeTypeBefore(const RuntimeTypeInfo& lhs, const RuntimeTypeInfo& rhs) noexcept;

  // Compatibility alias for older autogenerated headers that used `moho::type_info`.
  using type_info [[deprecated("Use moho::RuntimeTypeInfo")]] = RuntimeTypeInfo;
} // namespace moho
